CREATE TABLE "category" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "name" text NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "product" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "asin" varchar(10) NOT NULL,
  "title" text NOT NULL,
  "description" text NOT NULL DEFAULT '',
  "img_url" varchar(70) NOT NULL,
  "product_url" varchar(40) NOT NULL,
  "stars" numeric(2,1) NOT NULL,
  "reviews" bigint NOT NULL,
  "price" numeric(10,2) NOT NULL,
  "list_price" numeric(10,2) NOT NULL,
  "category_id" bigint NOT NULL,
  "is_best_seller" bool NOT NULL,
  "bought_in_last_month" bigint NOT NULL DEFAULT 0,
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "account" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "username" text NOT NULL,
  "password_hash" text NOT NULL,
  "first_name" text NOT NULL,
  "last_name" text NOT NULL,
  "address" text NOT NULL,
  "phone" text NOT NULL,
  "reviewer_name" text NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "review" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "product_id" bigint NOT NULL,
  "account_id" bigint NOT NULL,
  "stars" numeric(1,0) NOT NULL,
  "review" text
);

CREATE TABLE "session" (
  "session_uuid" text UNIQUE PRIMARY KEY NOT NULL,
  "cart_id" BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
  "account_id" bigint NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "modified_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "cart_item" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "cart_id" bigint NOT NULL,
  "product_id" bigint NOT NULL,
  "quantity" integer DEFAULT 1,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "modified_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "order" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "account_id" bigint NOT NULL,
  "total" numeric(12,2) NOT NULL,
  "discount_id" bigint DEFAULT null,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "modified_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "order_item" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "order_id" bigint NOT NULL,
  "product_id" bigint NOT NULL,
  "quantity" integer DEFAULT 1,
  "price" numeric(10,2) NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "modified_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "payment" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "order_id" bigint NOT NULL,
  "provider" text NOT NULL,
  "amount" numeric(12,2) NOT NULL,
  "status" text NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "modified_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "discount" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "type" text NOT NULL,
  "amount" float DEFAULT 0,
  "expires_at" timestamp NOT NULL DEFAULT (now()),
  "created_by" bigint NOT NULL,
  "modified_by" bigint NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "modified_at" timestamp NOT NULL DEFAULT (now())
);

ALTER TABLE "product" ADD CONSTRAINT "product_category_fk" FOREIGN KEY ("category_id") REFERENCES "category" ("id");

ALTER TABLE "cart_item" ADD CONSTRAINT "fk_cart_session" FOREIGN KEY ("cart_id") REFERENCES "session" ("cart_id");

ALTER TABLE "order" ADD CONSTRAINT "fk_order_account" FOREIGN KEY ("account_id") REFERENCES "account" ("id");

ALTER TABLE "order" ADD CONSTRAINT "fk_order_discount" FOREIGN KEY ("discount_id") REFERENCES "discount" ("id");

ALTER TABLE "order_item" ADD CONSTRAINT "fk_order_orderitems" FOREIGN KEY ("order_id") REFERENCES "order" ("id");

ALTER TABLE "order_item" ADD CONSTRAINT "fk_order_products" FOREIGN KEY ("product_id") REFERENCES "product" ("id");

ALTER TABLE "order" ADD CONSTRAINT "fk_payment_order" FOREIGN KEY ("id") REFERENCES "payment" ("id");
